spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/alertdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  scheduler:
    fixed-delay-ms: 120000

app:
  seed:
    enabled: true
  jwt:
    secret: change-me-to-a-very-long-secret-key-min-32-chars
    expiration-ms: 86400000

alerts:
  expiry-mins: 1440
  scheduler:
    fixed-delay-ms: 120000
